import type { NitroConfig } from "nitro";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import {
  scanRoutesDirectory,
  generateRouteManifestArrays,
  generateImportStatements,
} from "./route-utils.js";
import type { OxideConfig } from "./config.js";
import { setConfig } from "./config.js";

interface WithOxideOptions extends OxideConfig {}

/**
 * Configures Nitro with Oxide framework support.
 *
 * This function sets up:
 * - Route discovery and manifest generation
 * - Client-side hydration entry point
 * - Virtual modules for SSR
 * - Server handlers for navigation payloads
 *
 * @param options - Configuration options
 * @returns Nitro configuration object
 */
export function withOxide(options: WithOxideOptions = {}): NitroConfig {
  const routesDir = options.routesDir ?? "src/routes";
  const trailingSlash = options.trailingSlash ?? "never";

  setConfig({
    routesDir,
    trailingSlash,
  });

  /**
   * Generates the .oxide/client.ts entry point for client-side hydration.
   * This file imports all routes and initializes the client router.
   */
  const generateClientEntry = () => {
    const oxideDir = resolve(process.cwd(), ".oxide");
    mkdirSync(oxideDir, { recursive: true });

    const routesDirPath = resolve(process.cwd(), routesDir);
    const { routes, layouts, errors } = scanRoutesDirectory(routesDirPath);

    const { routeImports, layoutImports, errorImports } = generateImportStatements(
      routes,
      layouts,
      errors,
      routesDir,
      "../",
    );

    const {
      routesArray,
      layoutsArray,
      errorsArray,
      routeComponentsMap,
      layoutComponentsMap,
      errorComponentsMap,
    } = generateRouteManifestArrays(routes, layouts, errors, routesDir);

    const clientEntry = `import "../src/app.css";
    import { initializeOxideRouter } from "oxidejs/client";
    import { setConfig } from "oxidejs";
    import LayoutRenderer from "oxidejs/components/LayoutRenderer.svelte";
    import ErrorRenderer from "oxidejs/components/ErrorRenderer.svelte";

    setConfig({
      routesDir: "${routesDir}",
      trailingSlash: "${trailingSlash}"
    });

${routeImports}
${layoutImports}
${errorImports}

const routes = [
${routesArray}
];

const layouts = [
${layoutsArray}
];

const errors = [
${errorsArray}
];

const routeComponents = {
${routeComponentsMap}
};

const layoutComponents = {
${layoutComponentsMap}
};

const errorComponents = {
${errorComponentsMap}
};

function importRoute(handler) {
  const component = routeComponents[handler] || layoutComponents[handler] || errorComponents[handler];
  if (!component) {
    console.error("Route component not found:", handler);
    return Promise.reject(new Error(\`Component not found: \${handler}\`));
  }
  return Promise.resolve({ default: component });
}

function importRouteAssets(handler) {
  return Promise.resolve({});
}

const routeManifest = {
  routes,
  layouts,
  errors,
  importRoute,
  importRouteAssets,
  LayoutRenderer,
  ErrorRenderer
};

initializeOxideRouter(routeManifest);
`;

    writeFileSync(resolve(oxideDir, "client.ts"), clientEntry);
  };

  return {
    hooks: {
      "dev:prepare": generateClientEntry,
      "build:before": generateClientEntry,
    },
    renderer: {
      handler: "src/renderer.ts",
    },
    errorHandler: "src/error.ts",
    routeRules: {
      "/__oxide/payload/**": {
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": "no-cache, no-store, must-revalidate",
        },
      },
      "/assets/**": {
        headers: {
          "Cache-Control": "public, max-age=31536000, immutable",
        },
      },
      "/**": {
        headers: {
          "Cache-Control": "no-cache",
        },
      },
    },
    serverHandlers: [
      {
        route: "/__oxide/payload/**",
        handler: "./src/payload.ts",
      },
    ],
    virtual: {
      /**
       * Virtual module that provides the route manifest for SSR.
       * This is dynamically generated by scanning the routes directory.
       */
      "#oxide/routes": () => {
        const routesDirPath = resolve(process.cwd(), routesDir);
        const { routes, layouts, errors } = scanRoutesDirectory(routesDirPath);

        const { routeImports, layoutImports, errorImports } = generateImportStatements(
          routes,
          layouts,
          errors,
          routesDir,
          "../../",
        );

        const {
          routesArray,
          layoutsArray,
          errorsArray,
          routeComponentsMap,
          layoutComponentsMap,
          errorComponentsMap,
        } = generateRouteManifestArrays(routes, layouts, errors, routesDir);

        return `
import LayoutRenderer from 'oxidejs/components/LayoutRenderer.svelte';
import ErrorRenderer from 'oxidejs/components/ErrorRenderer.svelte';

${routeImports}
${layoutImports}
${errorImports}

const routes = [
${routesArray}
];

const layouts = [
${layoutsArray}
];

const errors = [
${errorsArray}
];

const routeComponents = {
${routeComponentsMap}
};

const layoutComponents = {
${layoutComponentsMap}
};

const errorComponents = {
${errorComponentsMap}
};

function importRoute(handler) {
  const component = routeComponents[handler] || layoutComponents[handler] || errorComponents[handler];
  if (!component) {
    console.error('Route component not found:', handler);
    return Promise.reject(new Error(\`Component not found: \${handler}\`));
  }
  return Promise.resolve({ default: component });
}

function importRouteAssets(handler) {
  return Promise.resolve({});
}

export default {
  routes,
  layouts,
  errors,
  importRoute,
  importRouteAssets,
  LayoutRenderer,
  ErrorRenderer
};
`;
      },
    },
  };
}
